name: ğŸ iOS Build (Final & Clean)

on:
  push:
    
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: â¬‡ï¸ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ¦ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: âš™ï¸ Install Dependencies
        run: flutter pub get

      - name: ğŸ› ï¸ Add iOS Camera & Photo Permissions
        run: |
          /usr/libexec/PlistBuddy -c "Add :NSCameraUsageDescription string 'á»¨ng dá»¥ng cáº§n truy cáº­p camera Ä‘á»ƒ quÃ©t vÃ  chá»¥p áº£nh cÃ´ng viá»‡c.'" "ios/Runner/Info.plist"
          /usr/libexec/PlistBuddy -c "Add :NSPhotoLibraryUsageDescription string 'á»¨ng dá»¥ng cáº§n truy cáº­p thÆ° viá»‡n áº£nh Ä‘á»ƒ báº¡n cÃ³ thá»ƒ chá»n áº£nh.'" "ios/Runner/Info.plist"

      - name: ğŸ“¦ Build and Package IPA
        run: flutter build ipa --release --no-codesign

      - name: â¬†ï¸ Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: QLTinHoc-IPA
          path: build/ios/ipa/*.ipa
